name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '21' # Set this to the version of Java used by your project
        distribution: 'temurin' # This is an example; use the distribution that fits your project

    - name: Build with Maven
      run: |
        cd kumpula-games-backend
        mvn -B package -Pjooq

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.RSA_KEY }}

    - name: Copy project files to Digital Ocean droplet
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.DO_HOST }} "mkdir -p /root/kumpula-app"
        scp -o StrictHostKeyChecking=no -r ./docker-compose.yml ${{ secrets.SSH_USERNAME }}@${{ secrets.DO_HOST }}:/root/kumpula-app/docker-compose.yml
        scp -o StrictHostKeyChecking=no -r ./nginx.conf ${{ secrets.SSH_USERNAME }}@${{ secrets.DO_HOST }}:/root/kumpula-app/nginx.conf

    - name: Build and Push Docker images
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker-compose build
        docker-compose push

    - name: Deploy to Digital Ocean
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.DO_HOST }} << 'EOF'
          cd /kumpula-app
          docker-compose pull
          docker-compose up -d
          # Any other commands needed for deployment like migrations
        EOF
